### ISSUE TITLE
Indonesian translations

### ISSUE THREAD

**Issue by nathansam** [ropensci/datefixR#107]
Thank you for offering to help with Indonesian translations @chitrams (https://github.com/ropensci/datefixR/issues/77)!

The easiest way for you to help with translations is likely via Gitlocalize. If you use the following link, you should be able to provide translations for the files used to translate warnings/errors (once you click on the Indonesian option, there will be one file for messages raised within R and another for messages raised within C++ code). Once you have finished writing translations, you can use Gitlocalize to open a pull request. https://gitlocalize.com/repo/8364 

Would you be also interested in helping to add support for Indonesian date formats? Would it just be a case of needing to add translations for names of months, or are dates given in different formats?

**Comment by chitrams** [comment]
Great, thank you :) 

As for dates it's only the case of month names that changes; the format remains the same.

I've started translating and have a few questions:

1. Should 'date' in "Unable to resolve date for subject" remain in english? Same question with "(date:" and "date should be a character"; is it a variable name that will remain the same?
2. How about "Month not in expected range" and "Day not in expected range"?

Thank you :)

**Comment by chitrams** [comment]
I've added the translation for month names in PR #108 :)

**Comment by nathansam** [comment]
Thank you! In all of these examples, they should be replaced with translations. The variable names (which should not be translated) are 
* `day.impute`
* `month.impute`
* `df`
* `col.names`
* `format`
* `theme`
There's also a couple of references to R's data types which usually aren't translated either:
* dataframe
* character
* vector

**Comment by chitrams** [comment]
Ah okay, will do. Thank you! 😄

**Comment by nathansam** [comment]
Hi @chitrams, thank for the work you have done already! There appears to be one translation left `format should be either 'dmy' or 'mdy'`. The "should be either" needs to be translated with the other words left as they are. Could you please do this translation when you have the time, and then I can open a PR for it 😄?

**Comment by chitrams** [comment]
Hi @nathansam thank you for following up on this! I was going to ask my mum how she usually sees "dmy" in Indonesia as I wasn't sure if we had an equivalent abbreviation 😆 I'm aiming to get this done before the end of the week.

Thank you for your patience and I do apologise for the delay, I'm in the middle of a server move at work and that's been a bit time consuming!

Cheers 😃

**Comment by chitrams** [comment]
Hi @nathansam I'm pretty happy with the translations now and have submitted them for review :)

**Comment by nathansam** [comment]
Thank you so much @chitrams! The translations should merge into the `main` branch soon, and I will submit an update to CRAN later today 😄.
