### ISSUE TITLE
Translate warnings/errors to French

### ISSUE THREAD

**Issue by nathansam** [ropensci/datefixR#40]
The warnings and errors can be given in French by making edits to the [the French translation file](/ropensci/datefixR/tree/devel/po/R-fr.po). Translations (`msgstr`) need to be provided for each English line (`msgid`).  Running the below R code should then update the package to use these translations.  

``` R
tools::update_pkg_po(".")
```

**Comment by KittJonathan** [comment]
Hi Nathan, I can work on that issue

**Comment by nathansam** [comment]
Thank you!
