### ISSUE TITLE
Create a Twitter account for the package

### ISSUE THREAD

**Issue by KittJonathan** [ropensci/datefixR#45]
Just a random thought ... The {gt} package has a Twitter account [https://twitter.com/gt_package](https://twitter.com/gt_package), which is really useful to keep up to date with new releases. Would it be something to consider for datefixR ?

**Comment by nathansam** [comment]
I think this is a good idea, thanks! A concern of mine has been people have been following my main account for different reasons (either for my research or for datefixR) and they might see my posts for one or the other to be spam. This seems like a good solution to keep my research and datefixR more separate. I've created an account for it now:  https://twitter.com/datefixR
