### ISSUE TITLE
More prior art

### ISSUE THREAD

**Issue by dpprdan** [ropensci/datefixR#63]
You mention `lubridate::parse_date_time()` and `anytime::anydate()` (and the apparently abandoned {linelist})in the README, but there is more prior art in date parsing than those two.

## [`parsedate::parse_date()`](https://github.com/gaborcsardi/parsedate)

``` r
library(datefixR)
library(parsedate)

parse_date(exampledates$some.dates)
#> [1] "1992-05-02 UTC" "2020-01-04 UTC" "1996-05-01 UTC" "2020-05-01 UTC"
#> [5] "1996-02-04 UTC"
```

`parse_date()` can handle all `some.more.dates` individually, but somehow trips up with the vector.

``` r
parse_date(c("2015", "02/05/00", "05/1990", "jan 2020"))
#> [1] "2015-01-01 UTC" "2000-02-05 UTC" "1990-01-05 UTC" "2020-01-01 UTC"
parse_date("2012-08")
#> [1] "2012-08-01 UTC"
```

I expect it to be faster than datefixR, because it uses C code from the git date parser. It offers fewer customisation options compared to datefixR.

## [`readr::parse_date()`](https://readr.tidyverse.org/reference/parse_datetime.html)

``` r
library(readr)
#> 
#> Attaching package: 'readr'
#> The following object is masked from 'package:parsedate':
#> 
#>     parse_date

parse_date(exampledates$some.dates)
#> Warning: 4 parsing failures.
#> row col   expected      actual
#>   1  -- date like  02 05 92   
#>   2  -- date like  01-04-2020 
#>   4  -- date like  2020-may-01
#>   5  -- date like  02-04-96
#> [1] NA           NA           "1996-05-01" NA           NA
parse_date(exampledates$some.more.dates)
#> Warning: 5 parsing failures.
#> row col   expected   actual
#>   1  -- date like  2015    
#>   2  -- date like  02/05/00
#>   3  -- date like  05/1990 
#>   4  -- date like  2012-08 
#>   5  -- date like  jan 2020
#> [1] NA NA NA NA NA
```

This is a bit unfair, because one should define locale and a format.

``` r
parse_date("01/02/2010", "%d/%m/%Y")
#> [1] "2010-02-01"
parse_date("01/02/2010", "%m/%d/%Y")
#> [1] "2010-01-02"
parse_datetime("1 enero 2015", "%d %B %Y", locale = locale("es"))
#> [1] "2015-01-01 UTC"
parse_datetime("14 Maart 1962", "%d %B %Y", locale = locale("nl"))
#> [1] "1962-03-14 UTC"
```

## [`clock::date_parse()`](https://clock.r-lib.org/reference/date_parse.html)

`clock::date_parse()` is very similar to `readr::parse_date()`.

``` r
library(clock)

date_parse("January 5, 2020", format = "%B %d, %Y")
#> [1] "2020-01-05"
# but
date_parse("July 4th, 2020", format = "%B %d, %Y")
#> Warning: Failed to parse 1 string at location 1. Returning `NA` at that
#> location.
#> [1] NA

date_parse("3. Februar 2020", format = "%d. %B %Y", locale = clock_locale("de"))
#> [1] "2020-02-03"
```

## [`stringi::stri_datetime_parse()`](https://stringi.gagolewski.com/rapi/stri_datetime_format.html)

``` r
library(stringi)
```

Again, one needs to define the format

``` r
x <- c('2015-02-28', '2015-02-29')
stri_datetime_parse(x, 'yyyy-MM-dd')
#> [1] "2015-02-28 19:17:35 CET" NA
stri_datetime_parse(x, 'yyyy-MM-dd', lenient=TRUE)
#> [1] "2015-02-28 19:17:35 CET" "2015-03-01 19:17:35 CET"
stri_datetime_parse("14 Maart 1962", 'date_long', locale = 'nl')
#> [1] "1962-03-14 19:17:36 CET"
# alternatively
stri_datetime_parse("14 Maart 1962", 'dd MMMM yyyy', locale = 'nl')
#> [1] "1962-03-14 19:17:36 CET"

# apparently it uses the current date to fill-up incomplete dates
stri_datetime_now()
#> [1] "2022-10-17 19:17:35 CEST"
stri_datetime_parse("Mei 62", 'LLLL yy', locale = 'nl')
#> [1] "1962-05-17 19:17:36 CET"
```

The requirement to supply a format make `readr::parse_date()`, `clock::date_parse()`, and `stri_datetime_parse()` obviously unsuitable for vectors with mixed dates.

{stringi} builds on the [ICU library](https://unicode-org.github.io/icu/userguide/format_parse/datetime/), as you may know, and contains weekday and months symbols (names) in \~211 locales, see [`stringi::stri_datetime_symbols()`](https://stringi.gagolewski.com/rapi/stri_datetime_symbols.html). Both [{readr}](https://github.com/tidyverse/readr/blob/main/data-raw/date-symbols.R) and [{clock}](https://github.com/r-lib/clock/blob/main/data-raw/clock-labels.R) use these internally to be able to parse international dates (which also explains, why they all behave similarly when parsing dates).

**Comment by nathansam** [comment]
Thank you for all of these! I will have a think about the best way to present them in the README and then update it. I obviously don't want most of the readme file to just be discussing alternatives, but I think it is still important to list them.
