### ISSUE TITLE
Translations needed for DE, ES, FR for new messages

### ISSUE THREAD

**Issue by nathansam** [ropensci/datefixR#76]
Since the introduction of multi-byte characters, a warning has been issued to the user when `datefixR` is used in a locale which does not support multi-byte characters. Unfortunately, this warning was introduced after previous translations, so it is not currently translated. 

GitLocalize has now been set up which makes it much easier to do translations for `datefixR`. If you are interested in making a translation contribution, check out the GitLocalize page for this package (requires GitHub login)
https://gitlocalize.com/repo/8364

As before, I am happy to acknowledge contributors as translators in DESCRIPTION `(role = "trl")` 

Status by language 
- [x] DE
- [x] ES
- [x] FR

**Comment by KittJonathan** [comment]
Hi Nathan, I can work on the FR translations

**Comment by nathansam** [comment]
Thank you so much @KittJonathan! How was using GitLocalize? I'm hoping it is a better alternative to editing .po files locally using a text editor.

**Comment by dpprdan** [comment]
I suppose you should've received a review request @nathansam. For some reason gitlocalize did not (let me) open a PR, yet. But maybe that's on purpose?

As for the experience: GitLocalize did not open the edit boxes in Firefox when I clicked on them, so that's a bit weird. I guess it takes a little getting used to, but otherwise the experience seems fine so far.

**Comment by nathansam** [comment]
Thanks @dpprdan! It is a bit weird. If I login, I can see someone has made a request and then approve it (which generates an actual PR), but I don't have an email or anything like that to tell me to check on GitLocalize in the first place. I think contributors will typically also message before/after on the issue so that probably won't be an issue. 

A bit weird about the Firefox bug, but glad to hear the overall experience is fine! 

Thank you so much for your translation!

**Comment by ajpelu** [comment]
Hi @nathansam 
I've updated the Spanish translation using the gitlocalize-app, but It is my first time with gitlocalize-app. Please @nathansam confirm it was ok. 
Thanks

**Comment by nathansam** [comment]
Thank you so much @ajpelu ! It all looks good to me! PR is now opened and should auto merge soon.
