### ISSUE TITLE
Translate warnings/errors to Russian

### ISSUE THREAD

**Issue by nathansam** [ropensci/datefixR#84]
Thank you for offering to help with Russian translations @atsyplenkov (#77)! 

The easiest way for you to help with translations is likely via Gitlocalize. If you use the following link, you should be able to provide translations for the two files used to translate warnings/errors into Russian (there's one file for messages raised within R and another for messages raised within C++ code) https://gitlocalize.com/repo/8364/ru

Would you be also interested in helping to add support for Russian dates? I must admit, I am not at all familiar with Russian dates. Would it just be a case of needing to add translations for names of months, or are dates given in different formats to most other languages?  For example with French, I needed to add support for "1er" and Spanish required "de" to be supported as a separator for dates (like ".","-","/" etc. are).

**Comment by atsyplenkov** [comment]
Hi @nathansam!

Please take a look at my submissions on Gitlocalize. I would be happy to add support for Russian dates as well. However, since the Russian language has many declensions, it can be tricky. I need some time to think about workarounds. I will fork and submit a pull request as soon as I'm finished. Stay tuned!

**Comment by nathansam** [comment]
Thank you so much! Your translations have been implemented as of 10b6812aec80e8539ce40ccde89d59891f5e6f75. Are you happy to be attributed in the [DESCRIPTION](https://github.com/ropensci/datefixR/blob/main/DESCRIPTION) along the other translators? How would you like to be attributed? (You're also of course welcome to make a PR to update DESCRIPTION directly).

**Comment by nathansam** [comment]
Closed by #89
