### ISSUE TITLE
Allow 31 as day.impute

### ISSUE THREAD

**Issue by robin-hutchinson** [ropensci/datefixR#93]
As I'm calculating date ranges, I have been looking at how to use fix_date_df() to impute the last day of the month. Originally I was planning to impute 31 and then altering this for the other months:

df <- datefixR::fix_date_df(df, "date_end", day.impute = 31, month.impute = 12, excel = TRUE, roman.numeral = TRUE) %>%
dplyr::mutate(month = as.numeric(gsub("^.....", "", gsub("...$", "", date_end))),
                    date_end = dplyr::case_when(!grepl("31$", date_end) ~ date_end, # ignore non-imputed dates
                                         month %in% c(9,4,6,11)  ~ gsub("-31", "-30", date_end, fixed = TRUE), = months with 30 days
                                         month == 2 & as.numeric(gsub("\\-......$", "", date_end))%% 4 == 0 ~ gsub("-31", "-29", date_end, fixed = TRUE), # leap februaries
                                         month == 2 ~ gsub("-31", "-28", date_end, fixed = TRUE), # other februaries
                                         TRUE ~ date_end))

But this is  producing "Error: day.impute should be an integer between 1 and 28"

Could day.impute be expanded to allow 31?

**Comment by nathansam** [comment]
Absolutely! It was a simple way of ensuring days of the month never went out of bounds, but a system which takes into account the actual days in each month (factoring in leap years) is definitely needed. I'll get to work work on this.

**Comment by robin-hutchinson** [comment]
Thanks Nathan, let me know if I can be of any help!

**Comment by nathansam** [comment]
Thanks! I've just pushed a change to devel which allows `day.impute = 31`. Days won't go out of bounds for each month so setting `day.impute=31` will result in the last day of the month being imputed for missing days. At the moment the changes are on the `devel` branch. 

If you could please install from this branch, 

```R
remotes::install_github("ropensci/datefixR", "devel")
```

and let me know if that works for your use case, that would be great!

**Comment by robin-hutchinson** [comment]
Hi Nathan - it's definitely working, thanks!

**Comment by nathansam** [comment]
Brilliant! Thanks. I will merge into `main` now. The change should be propagated to CRAN in about two weeks.
